# Generated by Django 4.2 on 2025-10-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('idProdutos', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço do Produto')),
                ('estoque', models.IntegerField(verbose_name='Estoque do Produto')),
                ('descricao', models.TextField(verbose_name='Descrição do Produto')),
                ('imagem', models.TextField(verbose_name='Imagem do Produto')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria do Produto')),
                ('dataCriado', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação do Produto')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
